name: pocflutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  build_runner: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_localizations:
    sdk: flutter
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  hydrated_bloc: ^7.0.1
  intl: ^0.17.0
  json_serializable: ^4.1.4

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
